"""Update price column to Float

Revision ID: 0d7747f763fb
Revises: aaa090022cda
Create Date: 2024-07-10 16:03:43.999180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d7747f763fb'
down_revision = 'aaa090022cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inmueble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('ambientes', sa.Integer(), nullable=False),
    sa.Column('banos', sa.Integer(), nullable=False),
    sa.Column('metros_cuadrados', sa.Float(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inmuebles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inmuebles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('link', mysql.TEXT(), nullable=False),
    sa.Column('ambientes', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('banos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metros_cuadrados', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('inmueble')
    # ### end Alembic commands ###
