"""Initial migration

Revision ID: aaa090022cda
Revises: 
Create Date: 2024-07-10 01:23:10.607802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaa090022cda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inmuebles', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('ambientes',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('banos',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('metros_cuadrados',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inmuebles', schema=None) as batch_op:
        batch_op.alter_column('metros_cuadrados',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('banos',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('ambientes',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
